### ISSUE TITLE
Advanced Driver Options

### ISSUE THREAD

**Issue by foxcoding** [ScriptPup/sqltools-teradata-driver#18]
Teradata behaves differently depending on the Session Mode and Character Set that you select.
For instance, ACSII mode is case sensitive, and TMODE (Teradata or Default) is not.
Simply add an additional field to pass extra parameters if possible.

**Comment by ScriptPup** [comment]
Hi @foxcoding,

I was looking into this, but it looks like `Character Set` isn't supported by the Teradata-node driver.

Ref:
- https://github.com/Teradata/nodejs-driver/blob/develop/docs/CONNECTIONPARAMS.md 
- https://github.com/Teradata/nodejs-driver/issues/38

I'm going to close this one out for now since the request is unfortunately not possible. (TMODE is already implemented in current version). 

I'm happy to look into other required options, and if you want to put together a PR for any additional options to make it happen faster feel free. I should be able to get to testing and pushing PRs to main a bit faster now than I was able to for the last few months.
