### ISSUE TITLE
Problem using plugin on Remote SSH Server

### ISSUE THREAD

**Issue by zolee1982** [ScriptPup/sqltools-teradata-driver#3]
Hi,

I face the below problem while trying to use the plugin on a remote server, using Remote SSH.

When the VS Code try to load the plugin this error appears:
ERROR (ext): ERROR: Error loading plugin SQLTools Teradata Driver Plugin Request ls/RegisterPlugin failed with message: .vscode-server/extensions/scriptpup.sqltools-teradata-driver-0.3.5/node_modules/teradata-nodejs-driver/node_modules/ffi-napi/build/Release/ffi_bindings.node: invalid ELF header, {"code":-32603}

Please help me with resolving the issue.
Thanks in advance.

Best regards,
Zoltán Kolozsvári

**Comment by ScriptPup** [comment]
Hi Zoltán,
Could you provide some additional information for me so I know what to look for?
1. Host (local) information
    - What is the OS?
    - What version of VS code is installed?
    - What version of nodejs is installed (if any)?
2. What is the remote (server) OS?
   - What is the OS?
    - What other extensions are installed and working remotely?
3. Does the plugin work as expected locally, or do you receive the same/similar error?
4. Do other sqltools plugins work correctly? (Should give me an indication of whether the issue is in the core module or if it's in the plugin itself)

P.S. please do provide the above in case I'm wrong, however:
I suspect the issue is there are missing platform specific binaries. I haven't published to marketplace before and was unaware that publishing under multiple architectures wouldn't actually package them with the platform specific dependencies. We're looking into a solution for that presently.

**Comment by zolee1982** [comment]
Hi ScriptPup,

Thanks for the quick answer, i really appreciate that.

The answers would be:
1. Host (local) information 
    * OS: Windows 10 Enterprise 20H2
    * VS code installed: 1.62.1
    * nodejs installed: no
2. What is the remote (server) OS?  
    * OS: Red Hat Enterprise Linux release 8.4 (Ootpa)
    * Extensions working remotely: Code Spell Checker, Git Graph, Git History, Jira and Bitbucket (Atlassian Labs), Todo Tree, YAML
3. Does the plugin work as expected locally, or do you receive the same/similar error? Locally it's working fine.
4. Do other sqltools plugins work correctly? Yes, I've tried MySQL

Thanks in advance.

Regards,
Zoltán

**Comment by ScriptPup** [comment]
Perfect, thanks for the additional info Zoltán. Given this info I do believe the issue is the compiled packages being for windows regardless of the platform the package is pulled for. @adamtwo has been helping me out and getting me up to speed on the compiling packages necessary to support multi-platform. Give us a bit to figure that all out and we'll get the correct architecture-specific packages re-published.

**Comment by ScriptPup** [comment]
Hi Zoltán,

Version 0.3.6 was just published using a github workflow to build for each platform individually. When you have a chance please give it a shot and let me know if you're still seeing the same error message.

**Comment by adamtwo** [comment]
I've tested on my Mac and it worked like a charm!

**Comment by zolee1982** [comment]
I've tested it, it's working fine, thanks for you quick solving.
